### ISSUE TITLE
[Feature Request]: Have a utility function to parse the query result into valid JSON object

### ISSUE THREAD

**Issue by BrunoQuaresma** [fauna/fauna-js#185]
**Issue**
When trying to pass the fauna query result from the server to the FE or any client via API or server-side rendering it does not work out of the box when having complex fields in the result like a time object or an array of references.

PS: With FQL 10, I see the id field is directly returned from the document with its relationships as well ❤️ so maybe at this point, only the TimeStub object is not "JSON friendly"?

**Suggestion**
Have a `serializeToJSON` function to help with scenarios like the following:
```ts
export async function GET() {
  const fauna = new Client()
  const result = await fauna.query(fql`products.all(){ id, name, createdAt }`)
  return NextResponse.json(serializeToJSON(result))
}
```

Or even better if the `result` object could have a `toJSON` method.

**Comment by ptpaterson** [comment]
It might be appropriate to add `toJSON` overrides for `TimeStub` and `DateStub`  types which return the respective strings. We stayed away from that, so far, in favor of flexibility, but your point is well made!

> a few array-ish cases

Can you elaborate what those cases are?

**Comment by BrunoQuaresma** [comment]
> a few array-ish cases

You can ignore this part.

**Comment by ptpaterson** [comment]
Okay, thanks for following up!

**Comment by ptpaterson** [comment]
Hi @BrunoQuaresma. We reviewed the issue and this isn't something we are going to take up in this repo. We don't want to make any assumptions about how folks may want to serialize things like dates and times to JSON.

The underlying string value for dates and times can be accessed though. See:
- `TimeStub.isoString`
- `DateStub.dateString`

You can use these values as they are, or convert them to other time/date formats as appropriate for your own application.

**Comment by ptpaterson** [comment]
As an alternative, you can provide `JSON.stringify` with a "replacer" function like this:

```typescript
function faunaReplacer(key: string, value: any) {
  if (value instanceof TimeStub) {
    return value.isoString;
  }
  if (value instanceof DateStub) {
    return value.dateString;
  }

  return value;
}
```

then use like this

```typescript
  const response = await fauna.query(fql`products.all(){ id, name, createdAt }`)

  const serialized = JSON.stringify(response.data, faunaReplacer)
```

**Comment by BrunoQuaresma** [comment]
Sure, sounds good.
