### ISSUE TITLE
Error on client.close()

### ISSUE THREAD

**Issue by BrunoQuaresma** [fauna/fauna-js#186]
Hey folks, I created a utility function that runs Fauna queries + closes the connection when the query is done but I'm getting the following error:
```console
- event compiled successfully in 177 ms (468 modules)
- error node_modules/fauna/dist/node/index.js (362:16) @ _NodeHTTP2Client.request
- error NetworkError: The network connection encountered a problem.
```

The code of the function is:
```ts
import { Client, Query, QueryValue } from "fauna";

export function runQuery<TQueryValue extends QueryValue>(query: Query) {
  const client = new Client({
    secret: process.env.FAUNA_SECRET_KEY,
  });

  try {
    return client.query<TQueryValue>(query);
  } finally {
    client.close();
  }
}
```

I'm guessing the issue is with the `client.close()` because when I remove it, the error is gone.

**Comment by cleve-fauna** [comment]
@BrunoQuaresma Query returns a promise. You need to use async await or run close in a then after the query promise completes. You are likely hitting this because the client is closing before its fired off the request.

**Comment by cleve-fauna** [comment]
Try this:

```
export async function runQuery<TQueryValue extends QueryValue>(query: Query) {
  const client = new Client({
    secret: process.env.FAUNA_SECRET_KEY,
  });

  try {
    return await client.query<TQueryValue>(query);
  } finally {
    client.close();
  }
}
```

**Comment by cleve-fauna** [comment]
Hey @BrunoQuaresma please reopen if this does not fix your issue.
