### ISSUE TITLE
FAUNA_ENDPOINT Environment Variable Is Not Honored

### ISSUE THREAD

**Issue by andyvanosdale** [fauna/fauna-js#205]
In the README, it states that the `FAUNA_ENDPOINT` environment variable can be used to override the default endpoint client configuration setting. However, this is not getting honored when set.

From what I see in the code, this just has not been implemented yet. There is an endpoint configuration that does have locahost settings, so this can be worked around with:

```
const client = process.env.FAUNA_ENDPOINT : 
  new Client({
    endpoint: endpoints.local
  }) ?
  new Client()
```

Repro Steps:
index.ts
```ts
import { Client } from 'fauna'
const client = new Client()
console.log(client.clientConfiguration)
```
Terminal
```
export FAUNA_ENDPOINT=http://localhost:8443
# transpile index.ts to javascript
node index.js
```

The output will show the default endpoint configuration (https://db.fauna.com/) instead of the environment setting (http://localhost:8443).

**Comment by CLBray** [comment]
Thanks for this report, @andyvanosdale! We'll get this fixed up shortly.
