### ISSUE TITLE
Error "The query failed 1 validation check" is not helpful

### ISSUE THREAD

**Issue by BrunoQuaresma** [fauna/fauna-js#223]
I'm receiving this error when I'm trying to run a query:
```
Error [QueryCheckError]: The query failed 1 validation check
```
But it is not helpful 😞 . Would be nice to see what is this validation check error. 

Thank you

**Comment by mrispoli24** [comment]
I'm having the same issue on my end, works in the shell but the same error from the js driver.

**Comment by mrispoli24** [comment]
I figured it out in my case, if you look at the documentation on site the example looks like this:

![image](https://github.com/fauna/fauna-js/assets/5890462/7488d96a-2405-42e4-bbfa-9ce8d31167f6)

Which might lead you to build a function that looks something like this in your code:

```ts
const collection_query = (collectionName: string) => fql`Collection.create({ name: "${collectionName}" })`;
```

However this throws the non-descript error above. You can fix this by removing the quotes around the name attribute and all works fine.

```ts
const collection_query = (collectionName: string) => fql`Collection.create({ name: ${collectionName} })`;
```

Hope this helps someone else...

**Comment by macmv** [comment]
The error includes a `queryInfo.summary` field, which will include the more descriptive error (like what you would get on the dashboard). You can log this with a try catch:
```ts
try {
 client.query(...);
} catch (e) {
  console.error(e.queryInfo.summary);
}
```

The error message you're seeing is meant to be a one-line response, telling you the type of error that came back. So parse errors and typecheck errors just say "The query failed N validation checks," whereas something like an `abort` will fail with "The query aborted."

The summary is the error message you're looking for. I don't know how JS handles errors in general, and it looks like its a bit of a pain to log more fields on the actual error itself. We might be able to improve this slightly by making the message in the `Error` the summary, but I think that would conflict with existing behavior, and it would make the difference between the error message and summary less clear.

**Comment by BrunoQuaresma** [comment]
@macmv thx for letting me know about the `queryInfo.summary`.
