### ISSUE TITLE
Response Object

### ISSUE THREAD

**Issue by markgarrigan** [fauna/fauna-js#228]
What is the rational behind the response object having data.data? Couldn't the data just be in the upper data?

```js
const response = await DB.query(fql`Collection.index('something')`);
console.log(response.data.data)
```

**Comment by macmv** [comment]
`response` is the entire response from the driver. So it contains some extra fields like query stats, the timestamp when your query was completed, and the results of any `log` messages during the query.

`response.data` is the query result. So for example, with a simple query:
```ts
const response = await DB.query(fql`2 + 3`);
console.log(response.data); // logs 5
```

In your case, `Collection.index()` will return a `Set`. Sets have two fields, `data` and an optional `after` token. If your set is long enough, only the first page of results will be returned (in `data`), and you will need to continue paginating with the `after` token. See the docs on sets: https://docs.fauna.com/fauna/current/reference/reference/schema_entities/set/.

If you know that your set will be short, you can convert it to an array. Note that this will time out your query if your set is too long:
```ts
const response = await DB.query(fql`Collection.index('something').toArray()`);
console.log(response.data); // this now contains an array of documents
```

Naming both of those fields `data` can be a bit confusing, but each one serves a very different purpose.
