### ISSUE TITLE
Typescript: Property 'after' does not exist on type 'QuerySuccess<Page<T>>'

### ISSUE THREAD

**Issue by tbdsux** [fauna/fauna-js#291]
Property 'after' does not exist on type 'QuerySuccess<Page<T>>'

![image](https://github.com/user-attachments/assets/de15a75f-5a00-42e2-a7ad-73bb649f4f44)

I found the use of `Page<T>` from: https://github.com/fauna/js-sample-app

```js
const res = await client.query<T>(query)

res.after // type error: 'Property 'after' does not exist on type 'QuerySuccess<T>''
```

Checking the types:
`QuerySuccess` does not have `after` field while `Page` has `after`

UPDATE:
After more trying, seems to be the return types are just correct. I thought `.after` was available without having to use `Page<T>` like: `res.after`
```js
const res = await client.query<Page<T>>(query) // need to use Page<>

res.data.data // data
res.data.after // nextToken
```

**Comment by ptpaterson** [comment]
Hi @tbdsux You nailed it! Thank for the submission. Please don't hesitate to reach out if you catch anything else.
