### ISSUE TITLE
`timeout_ms` is not a great name/hard to document 

### ISSUE THREAD

**Issue by breathe** [fauna/fauna-js#33]
https://github.com/fauna/fauna-js/blob/f88926faafa87e1bfec31e7ade7277cfb3013392/src/client-configuration.ts#L22

I get that this derives its name from the wire protocol - however we have to expose this to driver consumers as well, and when documenting this in the drivers, the name is not great.  It will be easy to confuse this with other driver timeout properties -- `query_timeout_ms` would be a better name imo

**Comment by cleve-fauna** [comment]
THis change is being made in both the wire protocol and the driver. PR shortly

**Comment by ptpaterson** [comment]
Fixed by #73
